---
- name: Create a standardized Ansible project structure
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    project_name: "my-new-project"       # Edit this project name
    project_user: "{{ ansible_user }}"   # Possibly edite this line also
    project_root: "/home/{{ project_user }}/ansible-projects/{{ project_name }}"  # Change this line to alter where the projects are stored

  tasks:

    - name: Ensure base project directory exists
      ansible.builtin.file:
        path:  "{{ project_root }}"
        state: directory
        owner: "{{ project_user }}"
        group: "{{ project_user }}"
        mode:  0755


    - name: Create inventory file
      ansible.builtin.copy:
        dest:  "{{ project_root }}/inventory"
        owner: "{{ project_user }}"
        group: "{{ project_user }}"
        mode:  0644
        content: |
          [remoteservers]
          remote1.lab.example.com
          remote2.lab.example.com

          [controlhost]
          controlhost.lab.example.com

          [all:children]
          remoteservers
          controlhost

######### These tasks above might need to be changed to suit your project ##########



    - name: Create subdirectories for logs, artifacts, and group_vars/host_vars
      ansible.builtin.file:
        path: "{{ project_root }}/{{ item }}"
        state: directory
        owner: "{{ project_user }}"
        group: "{{ project_user }}"
        mode:  0755
      loop:
        - artifacts
        - log
        - group_vars
        - host_vars
        - templates
        - files
        - roles


    - name: Create site.yml playbook skeleton
      ansible.builtin.copy:
        dest:  "{{ project_root }}/site.yml"
        owner: "{{ project_user }}"
        group: "{{ project_user }}"
        mode:  0644
        content: |
          ---
          - name:     Example site playbook
            hosts:    remoteservers
            become:   true
            tasks:
              - name: Ping all hosts
                ansible.builtin.ping:

    - name: Create ansible-navigator.yml configuration file
      ansible.builtin.copy:
        dest:  "{{ project_root }}/ansible-navigator.yml"
        owner: "{{ project_user }}"
        group: "{{ project_user }}"
        mode:  0644
        content: |
          ---
          ansible-navigator:
            mode: interactive
            execution-environment:
              enabled:          true
              container-engine: podman
              image:            ghcr.io/ansible/creator-ee:v0.22.0
            playbook-artifact:
              enable:  true
              save-as: "./artifacts/{playbook_name}-{time_stamp}.json"
            logging:
              level:  info
              append: true
              file:   "./log/navigator.log"

    - name: Create ansible.cfg
      ansible.builtin.copy:
        dest:  "{{ project_root }}/ansible.cfg"
        owner: "{{ project_user }}"
        group: "{{ project_user }}"
        mode:  0644
        content: |
          [defaults]
          inventory = ./inventory
          remote_user = "{{ project_user }}"

          [privilege_escalation]
          become = true
          become_method = sudo
          become_ask_pass = false
          become_user = root


    - name: Display project structure summary
      ansible.builtin.debug:
        msg: |
          ✅ Ansible project structure created at {{ project_root }}
          ├── ansible-navigator.yml
          ├── inventory
          ├── site.yml
          ├── artifacts/
          ├── log/
          ├── group_vars/
          └── host_vars/
