---
- name: Create a standardized Ansible project structure
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    ### Edit these variables to reflect your circumstance
    project_name: "my-new-project"
    remote_user_name : ansible
    project_root: "/home/{{ remote_user_name }}/ansible-projects/{{ project_name }}"
    ee_image: "registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8:latest"

  tasks:
    - name: Ensure user exists (ansible UID 5000)
      ansible.builtin.user:
        name: "{{ remote_user_name }}"
        uid: 5000
        shell: /bin/bash
        create_home: true

    - name: Ensure base project directory exists
      ansible.builtin.file:
        path:  "{{ project_root }}"
        state: directory
        owner: "{{ remote_user_name }}"
        group: "{{ remote_user_name }}"
        mode:  0755


    - name: Create inventory file
      ansible.builtin.copy:
        dest:  "{{ project_root }}/inventory"
        owner: "{{ remote_user_name }}"
        group: "{{ remote_user_name }}"
        mode:  0644
        content: |
          [remoteservers]
          servera.lab.example.com
          serverb.lab.example.com

          [controlhost]
          workstation.lab.example.com

          [allhosts:children]
          remoteservers
          controlhost

######### These tasks above might need to be changed to suit your project ##########



    - name: Create subdirectories for logs, artifacts, and group_vars/host_vars
      ansible.builtin.file:
        path: "{{ project_root }}/{{ item }}"
        state: directory
        owner: "{{ remote_user_name }}"
        group: "{{ remote_user_name }}"
        mode:  0755
      loop:
        - artifacts
        - log
        - group_vars
        - host_vars
        - templates
        - files
        - roles


    - name: Create site.yml playbook skeleton
      ansible.builtin.copy:
        dest:  "{{ project_root }}/site.yml"
        owner: "{{ remote_user_name }}"
        group: "{{ remote_user_name }}"
        mode:  0644
        content: |
          ---
          - name:     Example site playbook
            hosts:    remoteservers
            become:   true
            tasks:
              - name: Ping all hosts
                ansible.builtin.ping:

    - name: Create ansible-navigator.yml configuration file
      ansible.builtin.copy:
        dest:  "{{ project_root }}/ansible-navigator.yml"
        owner: "{{ remote_user_name }}"
        group: "{{ remote_user_name }}"
        mode:  0644
        content: |
          ---
          ansible-navigator:
            mode: interactive
            execution-environment:
              enabled:          true
              container-engine: podman
              image:            "{{ ee_image }}"
            playbook-artifact:
              enable:  true
              save-as: "./artifacts/{playbook_name}-{time_stamp}.json"
            logging:
              level:  info
              append: true
              file:   "./log/navigator.log"

    - name: Create ansible.cfg
      ansible.builtin.copy:
        dest:  "{{ project_root }}/ansible.cfg"
        owner: "{{ remote_user_name }}"
        group: "{{ remote_user_name }}"
        mode:  0644
        content: |
          [defaults]
          inventory = ./inventory
          remote_user = "{{ remote_user_name }}"

          [privilege_escalation]
          become = true
          become_method = sudo
          become_ask_pass = false
          become_user = root


    - name: Display project structure summary
      ansible.builtin.debug:
        msg: |
          ✅ Ansible project structure created at {{ project_root }}
          ├── ansible-navigator.yml
          ├── inventory
          ├── site.yml
          ├── artifacts/
          ├── log/
          ├── group_vars/
          └── host_vars/
